#!/usr/bin/env sh

# Load scripting addition
# See this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Space labels
yabai -m space 1 --label "Browsing"
yabai -m space 2 --label "Coding"
yabai -m space 3 --label "Organisation"
yabai -m space 5 --label "University"
yabai -m space 7 --label "Media"
yabai -m space 8 --label "Guitar"

yabai -m rule --add app="Safari"                space=1
yabai -m rule --add app="Brave Browser"         space=1
yabai -m rule --add app="Google Chrome"         space=1
yabai -m rule --add app="Tor Browser"           space=1

# Code
yabai -m rule --add app="Code"    opacity=0.85  space=2
yabai -m rule --add app="iTerm2"                space=2

# external bar
# yabai -m config external_bar all:0:32

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.4
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   05

# disable tiling for apps

# ru

safari_title="(Основные|Вкладки|Автозаполнение|Пароли|Поиск|Безопасность|Веб-сайты|Расширения|Дополнения)"
yabai -m rule --add app="^Системные настройки$"                   manage=off
yabai -m rule --add app="^Finder$" title="(Свойства|Настройки)"   manage=off
# yabai -m rule --add app="^Safari$" title="$safari_title"          manage=off
yabai -m rule --add app="^Информация о системе$"                  manage=off
yabai -m rule --add app="^Калькулятор$"                           manage=off
yabai -m rule --add app="^Мониторинг системы$"                    manage=off
yabai -m rule --add app="^Шрифты$"                                manage=off
yabai -m rule --add label="App Store" app="^App Store$"           manage=off
yabai -m rule --add app="^Утилита архивирования$"                 manage=off
yabai -m rule --add app="^Keka$"                                  manage=off
yabai -m rule --add app="^Vimari$"                                manage=off
yabai -m rule --add app="^Installer$"                             manage=off
yabai -m rule --add app="^VimR$" title="(Preferences)"            manage=off
yabai -m rule --add app="^Цифровой колориметр$"                   manage=off
yabai -m rule --add app="^Twitter$" title="(Медиа)"               manage=off
yabai -m rule --add app="^Spark$"                                 manage=off

# eng

# safari_title="(General|Tabs|Autofill|Passwords|Search|Security|Privacy|Websites|Extensions|Advanced)"
# yabai -m rule --add app="^Safari$" title=$safari_title            manage=off
# yabai -m rule --add app="^System Preferences$"                    manage=off
# yabai -m rule --add app="^System Information$"                    manage=off
# yabai -m rule --add app="^Finder$" title="(Info|Preferences)"     manage=off
# yabai -m rule --add app="^Calculator$"                            manage=off
# yabai -m rule --add app="^Activity Monitor$"                      manage=off
# yabai -m rule --add app="^Font Book$"                             manage=off
# yabai -m rule --add app="^App Store$"                             manage=off
# yabai -m rule --add app="^Archive Utility$"                       manage=off
# yabai -m rule --add app="^Keka$"                                  manage=off
# yabai -m rule --add app="^Vimari$"                                manage=off
# yabai -m rule --add app="^Installer$"                             manage=off
# yabai -m rule --add app="^VimR$" title="(Preferences)"              manage=off
# yabai -m rule --add app="^Digital Colour Meter$"                    manage=off

echo "yabai configuration loaded.."

